export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";